import type { GuidePage } from './types';

const PLACEHOLDER = '/placeholder.svg?height=630&width=1200';

/**
 * The nine real King Kunta video guides. Their detailed method body, quick
 * answer, and FAQ are sourced from the MDX file at render time (mdxSlug); the
 * fields here drive listing cards, stats panels, and internal linking.
 */
const mdxGuides: GuidePage[] = [
  {
    title: 'Make 1,000,000 Gold With This Tiragarde Sound Route',
    slug: 'wow-gold-farm-1000000-tiragarde-sound-mining-herbalism-route',
    excerpt:
      'A repeatable BFA gathering loop in Tiragarde Sound for Monelite Ore, Storm Silver, and high-demand herbs.',
    seoTitle:
      'Tiragarde Sound Gold Farm in WoW: Gathering Route, Gold Per Hour, and Best Sell Time',
    metaDescription:
      'A repeatable Battle for Azeroth gathering route in Tiragarde Sound for ore and herbs, with gold-per-hour ranges and auction house selling notes.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'OUsoRkoMmgE',
    publishedAt: '2020-04-21',
    updatedAt: '2024-08-01',
    hub: 'farming',
    category: 'Farming Guides',
    subcategory: 'Herbalism',
    expansion: 'Battle for Azeroth',
    methodType: 'Gathering Route',
    goldPerHourLow: 2500,
    goldPerHourHigh: 4000,
    setupCost: 'Low',
    saleSpeed: 'Medium',
    riskLevel: 'Low',
    requirements: ['Mining', 'Herbalism recommended', 'Flying in BFA zones', 'Auction House addon'],
    whoFor: ['Gatherers', 'Solo players', 'Alts'],
    tldr: '',
    bestTimeToFarm: 'Off-peak hours when node competition is lowest',
    bestTimeToSell: 'Early week, when profession levelers refill mats',
    ahNotes: 'Post ore and herbs in buyer-friendly stack sizes; avoid dumping into a thin market.',
    realmCaveats: 'BFA mat demand varies heavily by realm population.',
    steps: [],
    analystTakeaway:
      'This is a pipeline farm, not a jackpot. Value compounds through consistent runs and disciplined listing.',
    faq: [],
    relatedGuides: ['wow-gold-farm-best-way-200k-iron-docks', 'wow-gold-farm-top-5-instant-respawn-gold-farms'],
    relatedVideos: ['OUsoRkoMmgE'],
    featured: true,
    canonicalUrl: '/guides/wow-gold-farm-1000000-tiragarde-sound-mining-herbalism-route',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-1000000-tiragarde-sound-mining-herbalism-route',
  },
  {
    title: '3 Expensive Items You Can Still Farm in WoW',
    slug: 'wow-gold-farm-3-expensive-items-transmog',
    excerpt:
      'Three rare transmog drops from old dungeons and raids that hold long-tail auction house value.',
    seoTitle: '3 Rare Transmog Farms in WoW: Drop Locations, Value, and Sell Strategy',
    metaDescription:
      'Farm three high-value rare transmog items from old WoW content and learn how to price and sell them on the auction house.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'O7kRzC3CMoM',
    publishedAt: '2020-04-07',
    updatedAt: '2024-08-01',
    hub: 'rare-farms',
    category: 'Rare Item & Transmog Farms',
    subcategory: 'Transmog',
    expansion: 'Classic+',
    methodType: 'Transmog Farm',
    goldPerHourLow: 1000,
    goldPerHourHigh: 8000,
    setupCost: 'Low',
    saleSpeed: 'Slow',
    riskLevel: 'High',
    requirements: ['Max-level character', 'Auction House addon', 'Patience for slow sales'],
    whoFor: ['Transmog sellers', 'Collectors', 'Patient flippers'],
    tldr: '',
    bestTimeToFarm: 'Any time; drops are RNG-gated',
    bestTimeToSell: 'List long and repost; wait for the right buyer',
    ahNotes: 'Do not panic-undercut rare appearances — one buyer sets the price.',
    realmCaveats: 'Transmog demand is far higher on high-population realms.',
    steps: [],
    analystTakeaway:
      'This is a portfolio play. You are building inventory of scarce appearances, not farming raw gold.',
    faq: [],
    relatedGuides: ['wow-gold-farm-goblin-power-shovel-150000', 'wow-gold-farm-southern-barrens-infinite-respawn-200k'],
    relatedVideos: ['O7kRzC3CMoM'],
    featured: false,
    canonicalUrl: '/guides/wow-gold-farm-3-expensive-items-transmog',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-3-expensive-items-transmog',
  },
  {
    title: 'Ghostlands & Amani Catacombs Chest Farm',
    slug: 'wow-gold-farm-600k-ghostlands-amani-catacombs',
    excerpt:
      'A fast old-world chest and transmog sweep around Sungraze Peak with high-upside RNG drops.',
    seoTitle: 'Ghostlands Chest & Transmog Farm in WoW: Route, Value, and Risk',
    metaDescription:
      'A fast chest and transmog farm in Ghostlands and the Amani Catacombs, with route notes and realistic value expectations.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'SrlI7UbKE1g',
    publishedAt: '2024-07-07',
    updatedAt: '2024-08-01',
    hub: 'rare-farms',
    category: 'Rare Item & Transmog Farms',
    subcategory: 'BoE Farming',
    expansion: 'Eastern Kingdoms',
    methodType: 'Transmog Farm',
    goldPerHourLow: 1500,
    goldPerHourHigh: 10000,
    setupCost: 'Low',
    saleSpeed: 'Medium',
    riskLevel: 'High',
    requirements: ['Lockpicking helps', 'Max-level character', 'Open bags'],
    whoFor: ['Transmog hunters', 'RNG-tolerant farmers'],
    tldr: '',
    bestTimeToFarm: 'Any time; a quick 6-minute cycle',
    bestTimeToSell: 'Repost transmog greens weekly',
    ahNotes: 'Price-check every green before vendoring.',
    realmCaveats: 'The 600k headline is a high-upside historical claim, not a per-run guarantee.',
    steps: [],
    analystTakeaway:
      'Short cycle time makes this efficient to repeat, but the upside is entirely drop-dependent.',
    faq: [],
    relatedGuides: ['wow-gold-farm-3-expensive-items-transmog'],
    relatedVideos: ['SrlI7UbKE1g'],
    featured: false,
    canonicalUrl: '/guides/wow-gold-farm-600k-ghostlands-amani-catacombs',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-600k-ghostlands-amani-catacombs',
  },
  {
    title: "Zul'Farrak Robes of Insight Route",
    slug: 'wow-gold-farm-80000-zulfarrak-robes-of-insight',
    excerpt:
      "Clear Zul'Farrak trash in Tanaris for Robes of Insight, Mageweave Cloth, and BoE greens.",
    seoTitle: "Zul'Farrak Transmog Farm in WoW: Robes of Insight Route and Sale Strategy",
    metaDescription:
      "Farm Zul'Farrak for the Robes of Insight and other rare transmog drops, with route notes, sale speed, and risk analysis.",
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'bf6pAyLJqfk',
    publishedAt: '2018-12-13',
    updatedAt: '2024-08-01',
    hub: 'rare-farms',
    category: 'Rare Item & Transmog Farms',
    subcategory: 'Transmog',
    expansion: 'Classic / Old World',
    methodType: 'Dungeon Farm',
    goldPerHourLow: 1000,
    goldPerHourHigh: 6000,
    setupCost: 'Low',
    saleSpeed: 'Slow',
    riskLevel: 'High',
    requirements: ['Max-level character', 'Auction House addon'],
    whoFor: ['Transmog sellers', 'Solo dungeon farmers'],
    tldr: '',
    bestTimeToFarm: 'Reset-friendly; farm across lockout resets',
    bestTimeToSell: 'List Robes of Insight long; it is a signature appearance',
    ahNotes: 'Mageweave Cloth gives steady baseline income between rare drops.',
    realmCaveats: 'Value depends heavily on rare drops and realm transmog demand.',
    steps: [],
    analystTakeaway:
      'The cloth income cushions the RNG, which makes this a more forgiving transmog farm than most.',
    faq: [],
    relatedGuides: ['wow-gold-farm-southern-barrens-infinite-respawn-200k'],
    relatedVideos: ['bf6pAyLJqfk'],
    featured: false,
    canonicalUrl: '/guides/wow-gold-farm-80000-zulfarrak-robes-of-insight',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-80000-zulfarrak-robes-of-insight',
  },
  {
    title: 'Iron Docks 200k Dungeon Farm',
    slug: 'wow-gold-farm-best-way-200k-iron-docks',
    excerpt:
      'A repeatable Warlords dungeon clear in Gorgrond for raw gold, Sumptuous Fur, and AH items.',
    seoTitle: 'Iron Docks Gold Farm in WoW: Route, Gold Per Hour, and Sale Notes',
    metaDescription:
      'Repeatable Iron Docks dungeon farm in Gorgrond for raw gold and materials, with gold-per-hour ranges and selling notes.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'Qzk3Op45AHo',
    publishedAt: '2024-01-15',
    updatedAt: '2024-08-01',
    hub: 'farming',
    category: 'Farming Guides',
    subcategory: 'Old Raid Runs',
    expansion: 'Warlords of Draenor',
    methodType: 'Dungeon Farm',
    goldPerHourLow: 3000,
    goldPerHourHigh: 6000,
    setupCost: 'Low',
    saleSpeed: 'Fast',
    riskLevel: 'Low',
    requirements: ['Max-level character', 'AoE class recommended'],
    whoFor: ['Solo players', 'Players who want reliable raw gold'],
    tldr: '',
    bestTimeToFarm: 'Any time; reliable per-run raw gold',
    bestTimeToSell: 'Sumptuous Fur sells best midweek',
    ahNotes: 'Most value is raw gold, so this is low-variance compared to transmog farms.',
    realmCaveats: 'Material prices vary, but raw gold is realm-agnostic.',
    steps: [],
    analystTakeaway:
      'The clearest beginner-safe farm here: predictable raw gold with low market risk.',
    faq: [],
    relatedGuides: ['wow-gold-farm-1000000-tiragarde-sound-mining-herbalism-route'],
    relatedVideos: ['Qzk3Op45AHo'],
    featured: true,
    canonicalUrl: '/guides/wow-gold-farm-best-way-200k-iron-docks',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-best-way-200k-iron-docks',
  },
  {
    title: 'Blackwing Descent Forgotten Farm',
    slug: 'wow-gold-farm-forgotten-farm-blackwing-descent',
    excerpt:
      'A solo Cataclysm raid clear for raw gold, Embersilk Cloth, and occasional BoE transmog.',
    seoTitle: 'Blackwing Descent Gold Farm in WoW: Raid Clear, Value, and Risk',
    metaDescription:
      'Solo the Blackwing Descent raid for raw gold, Embersilk Cloth, and transmog upside, with realistic value expectations.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'peiVNqeUTfI',
    publishedAt: '2024-01-15',
    updatedAt: '2024-08-01',
    hub: 'farming',
    category: 'Farming Guides',
    subcategory: 'Old Raid Runs',
    expansion: 'Cataclysm',
    methodType: 'Dungeon Farm',
    goldPerHourLow: 2000,
    goldPerHourHigh: 5000,
    setupCost: 'Low',
    saleSpeed: 'Medium',
    riskLevel: 'Medium',
    requirements: ['Max-level character', 'Weekly raid lockout awareness'],
    whoFor: ['Solo raid farmers', 'Cloth sellers'],
    tldr: '',
    bestTimeToFarm: 'Weekly, respecting the raid lockout',
    bestTimeToSell: 'Embersilk Cloth spikes when levelers need it',
    ahNotes: 'Raw gold plus cloth gives a stable floor with transmog upside on top.',
    realmCaveats: 'Lockout limits repeat runs; plan around the weekly reset.',
    steps: [],
    analystTakeaway:
      'Best treated as a weekly routine, not a grind — the lockout caps the per-week ceiling.',
    faq: [],
    relatedGuides: ['wow-gold-farm-best-way-200k-iron-docks'],
    relatedVideos: ['peiVNqeUTfI'],
    featured: false,
    canonicalUrl: '/guides/wow-gold-farm-forgotten-farm-blackwing-descent',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-forgotten-farm-blackwing-descent',
  },
  {
    title: 'Goblin Power Shovel — 150,000 Gold Transmog Weapon',
    slug: 'wow-gold-farm-goblin-power-shovel-150000',
    excerpt:
      'Farm Venture Co. mobs in Northern Stranglethorn for the rare Goblin Power Shovel appearance.',
    seoTitle: 'Goblin Power Shovel Farm in WoW: Drop Location, Value, and Sell Strategy',
    metaDescription:
      'Farm the rare Goblin Power Shovel transmog weapon in Northern Stranglethorn, with route notes and auction house sale strategy.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'oeAparF3JMY',
    publishedAt: '2024-01-15',
    updatedAt: '2024-08-01',
    hub: 'rare-farms',
    category: 'Rare Item & Transmog Farms',
    subcategory: 'Transmog',
    expansion: 'Classic / Old World',
    methodType: 'Transmog Farm',
    goldPerHourLow: 500,
    goldPerHourHigh: 12000,
    setupCost: 'Low',
    saleSpeed: 'Slow',
    riskLevel: 'High',
    requirements: ['High-level character to one-shot mobs', 'Fast movement / flight', 'Open bags'],
    whoFor: ['Rare-drop hunters', 'Transmog sellers'],
    tldr: '',
    bestTimeToFarm: 'Any time; keep movement near-constant',
    bestTimeToSell: 'Repost repeatedly; the buyer pool is small but pays big',
    ahNotes: 'Do not undercut aggressively — it slows future sales of a scarce item.',
    realmCaveats: 'The 150k value is upside potential, not guaranteed income.',
    steps: [],
    analystTakeaway:
      'High variance. Only worth it if you enjoy the hunt and can hold inventory for the right buyer.',
    faq: [],
    relatedGuides: ['wow-gold-farm-southern-barrens-infinite-respawn-200k', 'wow-gold-farm-3-expensive-items-transmog'],
    relatedVideos: ['oeAparF3JMY'],
    featured: false,
    canonicalUrl: '/guides/wow-gold-farm-goblin-power-shovel-150000',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-goblin-power-shovel-150000',
  },
  {
    title: 'Southern Barrens Infinite Respawn Farm',
    slug: 'wow-gold-farm-southern-barrens-infinite-respawn-200k',
    excerpt:
      'An infinite-respawn transmog farm at Bael Modan Excavation for cloth, greens, and rare recipes.',
    seoTitle: 'Southern Barrens Infinite Respawn Farm in WoW: Route, Value, and Risk',
    metaDescription:
      'Farm the infinite-respawn Bael Modan Excavation in Southern Barrens for transmog, Silk Cloth, and the Rich Purple Silk Shirt pattern.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'Pa5-bhFehXg',
    publishedAt: '2019-01-29',
    updatedAt: '2024-08-01',
    hub: 'rare-farms',
    category: 'Rare Item & Transmog Farms',
    subcategory: 'Transmog',
    expansion: 'Old World / Kalimdor',
    methodType: 'Transmog Farm',
    goldPerHourLow: 1500,
    goldPerHourHigh: 8000,
    setupCost: 'Low',
    saleSpeed: 'Slow',
    riskLevel: 'Medium',
    requirements: ['AoE class', 'Max-level character', 'Loot discipline'],
    whoFor: ['Transmog farmers', 'Recipe hunters'],
    tldr: '',
    bestTimeToFarm: 'Any time; tight loop with fast respawns',
    bestTimeToSell: 'Pattern: Rich Purple Silk Shirt lists long for premium buyers',
    ahNotes: 'Silk Cloth is your steady floor between rare recipe and transmog hits.',
    realmCaveats: 'Recipe demand and transmog pricing vary by realm.',
    steps: [],
    analystTakeaway:
      'The infinite respawn removes downtime, so gold/hour is more consistent than most transmog farms.',
    faq: [],
    relatedGuides: ['wow-gold-farm-80000-zulfarrak-robes-of-insight'],
    relatedVideos: ['Pa5-bhFehXg'],
    featured: false,
    canonicalUrl: '/guides/wow-gold-farm-southern-barrens-infinite-respawn-200k',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-southern-barrens-infinite-respawn-200k',
  },
  {
    title: 'Top 5 Instant Respawn Gold Farms',
    slug: 'wow-gold-farm-top-5-instant-respawn-gold-farms',
    excerpt:
      'Five fast-respawn routes across Outland and the old world for transmog, cloth, and materials.',
    seoTitle: 'Top 5 Instant Respawn Gold Farms in WoW: Routes, Gold Per Hour, and Sale Notes',
    metaDescription:
      'Five instant-respawn WoW farming routes for transmog and materials, with gold-per-hour ranges and selling strategy.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'btnbKgxNuK8',
    publishedAt: '2024-07-07',
    updatedAt: '2024-08-01',
    hub: 'farming',
    category: 'Farming Guides',
    subcategory: 'Mob Farms',
    expansion: 'The Burning Crusade / Classic+',
    methodType: 'Mob Farm',
    goldPerHourLow: 1500,
    goldPerHourHigh: 3500,
    setupCost: 'Low',
    saleSpeed: 'Medium',
    riskLevel: 'Medium',
    requirements: ['High-level AoE character (Druid, DH, Monk)', 'Auction House addon'],
    whoFor: ['Farmers who want variety', 'Transmog sellers'],
    tldr: '',
    bestTimeToFarm: 'Rotate routes to avoid competition',
    bestTimeToSell: 'Spread transmog listings across the week',
    ahNotes: 'Volume kills plus smart listing beat chasing any single rare drop.',
    realmCaveats: 'Gold/hour is server-dependent and market-variable.',
    steps: [],
    analystTakeaway:
      'Having five routes lets you rotate away from crowded farms — competition avoidance is the edge here.',
    faq: [],
    relatedGuides: ['wow-gold-farm-1000000-tiragarde-sound-mining-herbalism-route'],
    relatedVideos: ['btnbKgxNuK8'],
    featured: true,
    canonicalUrl: '/guides/wow-gold-farm-top-5-instant-respawn-gold-farms',
    schemaType: 'Article',
    mdxSlug: 'wow-gold-farm-top-5-instant-respawn-gold-farms',
  },
];

/** New fully-typed sample guides that fill out the AH, economy, and profession silos. */
const sampleGuides: GuidePage[] = [
  {
    title: 'WoW Auction House Flipping Guide: Safe Niches, Risk, and Sale Rate',
    slug: 'wow-auction-house-flipping-safe-niches',
    excerpt:
      'A data-analyst framework for auction house flipping: which niches are safe, how much capital you need, and how to read sale rate before you buy.',
    seoTitle: 'WoW Auction House Flipping Guide: Safe Niches, Risk, and Sale Rate',
    metaDescription:
      'Learn safe auction house flipping in WoW: low-risk niches, required capital, sale-rate analysis, and the market signals that tell you when to stop.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'btnbKgxNuK8',
    publishedAt: '2024-06-10',
    updatedAt: '2024-08-01',
    hub: 'auction-house',
    category: 'Auction House Flipping',
    subcategory: 'Flipping',
    expansion: 'Current Retail',
    methodType: 'Auction House',
    goldPerHourLow: 5000,
    goldPerHourHigh: 25000,
    setupCost: 'High',
    saleSpeed: 'Medium',
    riskLevel: 'Medium',
    requirements: ['Starting capital (50k+)', 'TradeSkillMaster or Auctionator', 'Daily posting time'],
    whoFor: ['Flippers', 'Players with capital', 'Market-minded players'],
    tldr:
      'Flip commodities and crafting mats with a proven sale rate rather than chasing rare snipes. Buy only when your expected margin survives undercut competition, and size positions to your capital so a bad flip cannot wipe you out.',
    bestTimeToFarm: 'Buy during weekend supply gluts when sellers dump stock',
    bestTimeToSell: 'Relist into weekday demand from raiders and crafters',
    ahNotes:
      'Sale rate matters more than margin. A 30% margin item that sells daily beats a 200% margin item that sells monthly.',
    realmCaveats: 'Thin low-pop realms have wide spreads but slow sale rates — size down accordingly.',
    steps: [
      { title: 'Pick a proven-demand niche', detail: 'Start with consumables and crafting mats that raiders rebuy every reset. Avoid vanity items until you understand sale rate.' },
      { title: 'Measure sale rate before buying', detail: 'Use TSM sale-rate data or track a market for a few days. Target items that clear at least ~20-30% of listings per day.' },
      { title: 'Set a max buyout by expected margin', detail: 'Only buy below the price where your margin survives being undercut twice. Never chase the last unit at a bad price.' },
      { title: 'Post in the right cadence', detail: 'Post smaller stacks more often to stay near the top of the list without dumping. Cancel-scan only where it is worth the time.' },
      { title: 'Cut losers fast', detail: 'If an item stops selling for two cycles, liquidate and move capital. Dead inventory is the real risk in flipping.' },
    ],
    analystTakeaway:
      'The edge in flipping is not finding the biggest margin — it is refusing to buy anything whose sale rate you have not verified. Treat capital like a portfolio and rebalance toward what actually clears.',
    faq: [
      { question: 'How much gold do I need to start flipping?', answer: 'You can start around 20-50k, but the strategy scales better with more capital because you can spread across several niches and absorb the occasional bad flip.' },
      { question: 'Is flipping risky?', answer: 'The main risk is dead inventory — gold tied up in items that stop selling. Verifying sale rate before buying and cutting losers quickly keeps risk low.' },
      { question: 'Do I need TradeSkillMaster?', answer: 'It is strongly recommended. Sale-rate and market-value data is the core of safe flipping. Auctionator works for simpler flips.' },
    ],
    relatedGuides: ['wow-crafting-arbitrage-materials', 'wow-economy-best-time-to-sell-mats'],
    relatedVideos: ['btnbKgxNuK8'],
    featured: true,
    canonicalUrl: '/guides/wow-auction-house-flipping-safe-niches',
    schemaType: 'Article',
  },
  {
    title: 'Crafting Material Arbitrage: Buy Raw, Sell Processed',
    slug: 'wow-crafting-arbitrage-materials',
    excerpt:
      'Buy raw materials cheap, convert them with a profession, and sell the processed goods into steady demand.',
    seoTitle: 'WoW Crafting Arbitrage Guide: Buy Raw Materials, Sell Processed for Profit',
    metaDescription:
      'Turn cheap raw materials into profit with crafting arbitrage in WoW. Learn which conversions pay, capital needs, and sale-rate strategy.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'btnbKgxNuK8',
    publishedAt: '2024-05-20',
    updatedAt: '2024-08-01',
    hub: 'auction-house',
    category: 'Auction House Flipping',
    subcategory: 'Crafting Arbitrage',
    expansion: 'Current Retail',
    methodType: 'Crafting',
    goldPerHourLow: 4000,
    goldPerHourHigh: 15000,
    setupCost: 'Medium',
    saleSpeed: 'Medium',
    riskLevel: 'Low',
    requirements: ['A processing profession', 'Auction House addon', 'Modest capital'],
    whoFor: ['Crafters', 'Flippers', 'Profession mains'],
    tldr:
      'When raw materials trade below the price of their processed form, buy the raw, convert it, and sell the output. This is one of the lowest-risk auction house plays because demand for processed goods is steady.',
    bestTimeToFarm: 'Buy raw mats during high-supply weekends',
    bestTimeToSell: 'Sell processed goods into weekday crafting demand',
    ahNotes: 'Watch for the spread collapsing when other crafters notice the same arbitrage.',
    realmCaveats: 'Conversion margins vary by realm; recompute weekly.',
    steps: [
      { title: 'Find a raw-vs-processed spread', detail: 'Compare the stack price of raw materials against the processed output (e.g. ore to bars, herbs to potions).' },
      { title: 'Confirm the output sells', detail: 'Check sale rate on the processed good. A wide spread means nothing if the output does not clear.' },
      { title: 'Batch convert', detail: 'Process in volume to minimize clicking, but do not over-produce past daily demand.' },
      { title: 'List steadily', detail: 'Feed the market in small batches to hold price rather than crashing it.' },
    ],
    analystTakeaway:
      'Arbitrage margins decay as competitors pile in. The winners rotate between conversions weekly instead of camping a single one until it dies.',
    faq: [
      { question: 'Which professions are best for arbitrage?', answer: 'Any processing profession works — Alchemy, Jewelcrafting, Enchanting, and Blacksmithing all have reliable raw-to-processed spreads.' },
      { question: 'Is this safer than flipping rare items?', answer: 'Yes. Processed goods have steady, measurable demand, so your capital is rarely stuck the way it can be with vanity flips.' },
    ],
    relatedGuides: ['wow-auction-house-flipping-safe-niches', 'wow-professions-alchemy-flasks'],
    relatedVideos: ['btnbKgxNuK8'],
    featured: false,
    canonicalUrl: '/guides/wow-crafting-arbitrage-materials',
    schemaType: 'Article',
  },
  {
    title: 'Best Time to Sell Gathering Mats Each Week',
    slug: 'wow-economy-best-time-to-sell-mats',
    excerpt:
      'The weekly demand cycle for gathering materials, and how to time your listings around raid resets and profession leveling.',
    seoTitle: 'WoW Economy Guide: Best Time to Sell Gathering Materials Each Week',
    metaDescription:
      'A data-analyst breakdown of the weekly WoW material demand cycle: when ore, herbs, and cloth peak, and when to hold versus sell.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'OUsoRkoMmgE',
    publishedAt: '2024-07-01',
    updatedAt: '2024-08-01',
    hub: 'economy',
    category: 'WoW Economy Analysis',
    subcategory: 'Market Timing',
    expansion: 'Current Retail',
    methodType: 'Event Economy',
    goldPerHourLow: 0,
    goldPerHourHigh: 0,
    setupCost: 'None',
    saleSpeed: 'Fast',
    riskLevel: 'Low',
    requirements: ['A stockpile of mats', 'Auction House addon', 'Patience to hold'],
    whoFor: ['Gatherers', 'Crafters', 'Anyone sitting on materials'],
    tldr:
      'Gathering material demand follows a weekly cycle driven by the raid reset and profession leveling. Sell into the early-week demand spike, hold through the weekend glut, and never dump a full stockpile at once.',
    bestTimeToFarm: 'Farm on weekends when prices are low and you have time',
    bestTimeToSell: 'List into the Tuesday/Wednesday reset demand spike',
    ahNotes: 'Split stockpiles across several days to avoid crashing your own market.',
    realmCaveats: 'Reset day differs by region; adjust the cycle to your realm.',
    steps: [
      { title: 'Map your realm reset', detail: 'Identify your region reset day — demand for consumable mats spikes in the 24-48 hours after it.' },
      { title: 'Stockpile during the glut', detail: 'Weekend farmers flood supply, pushing prices down. That is your buy/hold window, not your sell window.' },
      { title: 'Meter your listings', detail: 'Release inventory in slices across the demand spike rather than in one dump.' },
      { title: 'Watch patch calendars', detail: 'New content and profession changes reset demand — mats can spike hard around a major patch.' },
    ],
    analystTakeaway:
      'Most players farm and sell in the same session, capturing the worst price. The entire edge is separating when you farm from when you sell.',
    faq: [
      { question: 'When do materials sell for the most?', answer: 'Typically in the 24-48 hours after the weekly raid reset, when raiders and crafters restock consumables.' },
      { question: 'Should I ever hold materials long term?', answer: 'Old-expansion mats often spike when players level professions or chase achievements. Holding can pay, but only if your realm has the demand.' },
    ],
    relatedGuides: ['wow-gold-farm-1000000-tiragarde-sound-mining-herbalism-route', 'wow-auction-house-flipping-safe-niches'],
    relatedVideos: ['OUsoRkoMmgE'],
    featured: true,
    canonicalUrl: '/guides/wow-economy-best-time-to-sell-mats',
    schemaType: 'Article',
  },
  {
    title: 'Alchemy Gold Guide: Flasks and Potions Market',
    slug: 'wow-professions-alchemy-flasks',
    excerpt:
      'How to make gold with Alchemy by supplying the flask and potion market that raiders rebuy every reset.',
    seoTitle: 'WoW Alchemy Gold Guide: Flasks, Potions, Gold Per Hour, and Sale Timing',
    metaDescription:
      'Make gold with Alchemy in WoW by supplying flasks and combat potions. Learn specialization priorities, margins, and the best time to sell.',
    heroImage: PLACEHOLDER,
    youtubeVideoId: 'btnbKgxNuK8',
    publishedAt: '2024-06-25',
    updatedAt: '2024-08-01',
    hub: 'professions',
    category: 'Professions for Gold',
    subcategory: 'Alchemy',
    expansion: 'Current Retail',
    methodType: 'Crafting',
    goldPerHourLow: 6000,
    goldPerHourHigh: 20000,
    setupCost: 'Medium',
    saleSpeed: 'Fast',
    riskLevel: 'Low',
    requirements: ['Alchemy (specialized)', 'Herb supply or capital to buy', 'Auction House addon'],
    whoFor: ['Profession mains', 'Raiders', 'Consistent-income seekers'],
    tldr:
      'Flasks and combat potions are consumed every raid night, so demand is steady and sale rate is high. Specialize for extra procs, buy herbs during the weekend glut, and sell into the post-reset raid demand.',
    bestTimeToFarm: 'Buy herbs cheap on weekends',
    bestTimeToSell: 'Sell flasks into raid nights after the weekly reset',
    ahNotes: 'Flasks are a commodity — proc-based specialization is where the real margin comes from.',
    realmCaveats: 'Competition is high on big realms, but so is volume; margins are thinner but sales are faster.',
    steps: [
      { title: 'Specialize for procs', detail: 'Put specialization points into the flasks/potions your realm consumes most to gain free extra output per craft.' },
      { title: 'Source herbs cheaply', detail: 'Buy herbs during weekend supply gluts or farm them yourself to control input cost.' },
      { title: 'Batch craft around resets', detail: 'Craft ahead of the weekly reset so you have stock ready for peak raid demand.' },
      { title: 'Post in raid windows', detail: 'List flasks in the evening hours when guilds are stocking for the night.' },
    ],
    analystTakeaway:
      'Alchemy is the most reliable profession income because consumption is guaranteed every reset. The margin lives in specialization procs, not the base recipe.',
    faq: [
      { question: 'Is Alchemy still good for gold?', answer: 'Yes. Flasks and potions are consumed continuously by raiders and are among the most reliable, fastest-selling profession goods.' },
      { question: 'Do I need to farm my own herbs?', answer: 'No, but controlling input cost — by farming or buying during gluts — is what separates high and low margins.' },
    ],
    relatedGuides: ['wow-crafting-arbitrage-materials', 'wow-economy-best-time-to-sell-mats'],
    relatedVideos: ['btnbKgxNuK8'],
    featured: false,
    canonicalUrl: '/guides/wow-professions-alchemy-flasks',
    schemaType: 'Article',
  },
];

export const guides: GuidePage[] = [...mdxGuides, ...sampleGuides];
