import type { VideoPage } from './types';

export const videos: VideoPage[] = [
  {
    title: '600,000 Gold in 6 Minutes — Ghostlands Chest Farm',
    slug: '600k-ghostlands-chest-farm',
    youtubeVideoId: 'SrlI7UbKE1g',
    excerpt: 'A fast old-world chest and transmog sweep with huge RNG upside.',
    summary:
      'King Kunta runs a rapid chest and transmog cycle through Ghostlands and the Amani Catacombs. The route prioritizes locked chests, cloth, and BoE greens that carry transmog value, and shows how to keep the loop under seven minutes.',
    publishedAt: '2024-07-07',
    duration: '6:00',
    hub: 'rare-farms',
    topic: 'Rare & Transmog Farms',
    promise: 'A repeatable 6-minute cycle with high-upside chest drops.',
    keyTakeaways: [
      'The loop is short enough to repeat many times per session',
      'Lockpicking adds chest access and value',
      'Price-check every green before vendoring',
      'The 600k headline is upside, not a per-run guarantee',
    ],
    timestamps: [
      { time: '0:00', label: 'Intro and route overview' },
      { time: '1:10', label: 'Sungraze Peak chest path' },
      { time: '3:20', label: 'Amani Catacombs sweep' },
      { time: '5:00', label: 'Auction house and pricing notes' },
    ],
    mentioned: ['Lockpicking', 'Amani Catacombs', 'Sungraze Peak', 'TradeSkillMaster'],
    relatedGuideSlug: 'wow-gold-farm-600k-ghostlands-amani-catacombs',
    relatedVideos: ['top-5-instant-respawn-farms', 'iron-docks-200k'],
    featured: true,
  },
  {
    title: 'The Top 5 Instant Respawn Gold Farms',
    slug: 'top-5-instant-respawn-farms',
    youtubeVideoId: 'btnbKgxNuK8',
    excerpt: 'Five fast-respawn routes you can rotate to dodge competition.',
    summary:
      'A tour of five instant-respawn farming routes across Outland and the old world. Each is chosen for tight pathing and fast respawns so you can rotate between them when a farm gets crowded.',
    publishedAt: '2024-07-07',
    duration: '15:42',
    hub: 'farming',
    topic: 'Farming Routes',
    promise: 'A rotation of five routes so you are never stuck on a crowded farm.',
    keyTakeaways: [
      'Rotate routes to avoid competition',
      'AoE classes clear tight packs fastest',
      'Volume of kills beats chasing one rare drop',
      'Spread transmog listings across the week',
    ],
    timestamps: [
      { time: '0:00', label: 'Intro' },
      { time: '1:30', label: 'Route 1 — Northern Stranglethorn' },
      { time: '4:45', label: 'Route 2 — Feralas' },
      { time: '8:00', label: 'Route 3 — Shadowmoon Valley' },
      { time: '11:15', label: 'Routes 4 & 5 — Nagrand and Blade\u2019s Edge' },
    ],
    mentioned: ['Druid', 'Demon Hunter', 'Monk', 'Northern Stranglethorn', 'Nagrand'],
    relatedGuideSlug: 'wow-gold-farm-top-5-instant-respawn-gold-farms',
    relatedVideos: ['600k-ghostlands-chest-farm', 'tiragarde-gathering-route'],
    featured: true,
  },
  {
    title: 'The Best Way to Make 200,000 Gold — Iron Docks',
    slug: 'iron-docks-200k',
    youtubeVideoId: 'Qzk3Op45AHo',
    excerpt: 'A low-risk dungeon farm with predictable raw gold.',
    summary:
      'A repeatable Iron Docks clear in Gorgrond that leans on raw gold and Sumptuous Fur rather than RNG drops, making it one of the most beginner-safe farms on the channel.',
    publishedAt: '2024-01-15',
    duration: '7:00',
    hub: 'farming',
    topic: 'Dungeon Farms',
    promise: 'Reliable raw gold with almost no market risk.',
    keyTakeaways: [
      'Raw gold makes this low-variance',
      'AoE class clears trash fastest',
      'Sumptuous Fur is a steady secondary income',
      'Great starter farm for new gold-makers',
    ],
    timestamps: [
      { time: '0:00', label: 'Intro' },
      { time: '1:00', label: 'Entrance and pull strategy' },
      { time: '3:30', label: 'Boss skips and route' },
      { time: '5:30', label: 'Reset and repeat' },
    ],
    mentioned: ['Iron Docks', 'Gorgrond', 'Sumptuous Fur'],
    relatedGuideSlug: 'wow-gold-farm-best-way-200k-iron-docks',
    relatedVideos: ['top-5-instant-respawn-farms'],
    featured: true,
  },
  {
    title: '1,000,000 Gold Tiragarde Sound Gathering Route',
    slug: 'tiragarde-gathering-route',
    youtubeVideoId: 'OUsoRkoMmgE',
    excerpt: 'A repeatable BFA ore and herb loop for steady material income.',
    summary:
      'A gathering circuit through Tiragarde Sound optimized for continuous movement. King Kunta shows how to sweep ore and herb nodes together and turn the volume into a long-term material pipeline.',
    publishedAt: '2020-04-21',
    duration: '10:15',
    hub: 'farming',
    topic: 'Gathering Routes',
    promise: 'A gathering loop you can bank on run after run.',
    keyTakeaways: [
      'Keep moving — volume beats waiting on nodes',
      'Mining + Herbalism doubles node density',
      'List mats in buyer-friendly stacks',
      'A pipeline farm, not a jackpot',
    ],
    timestamps: [
      { time: '0:00', label: 'Intro and route map' },
      { time: '2:00', label: 'Kennings Lodge to Bridgeport' },
      { time: '5:30', label: 'Winterdeep Basin sweep' },
      { time: '8:00', label: 'Selling and pricing' },
    ],
    mentioned: ['Monelite Ore', 'Storm Silver Ore', 'Tiragarde Sound', 'Druid'],
    relatedGuideSlug: 'wow-gold-farm-1000000-tiragarde-sound-mining-herbalism-route',
    relatedVideos: ['top-5-instant-respawn-farms', 'iron-docks-200k'],
    featured: false,
  },
  {
    title: 'Goblin Power Shovel — 150,000 Gold Transmog Weapon',
    slug: 'goblin-power-shovel',
    youtubeVideoId: 'oeAparF3JMY',
    excerpt: 'Hunt a rare old-world transmog weapon with big buyer upside.',
    summary:
      'A rare-drop hunt for the Goblin Power Shovel in Northern Stranglethorn. The video demonstrates the one-shot farming loop and explains how to sell a scarce appearance without crashing its price.',
    publishedAt: '2024-01-15',
    duration: '5:10',
    hub: 'rare-farms',
    topic: 'Rare & Transmog Farms',
    promise: 'A scarce appearance that pays big for the right buyer.',
    keyTakeaways: [
      'One-shot mobs and keep moving',
      'Every green could be a transmog hit',
      'Do not undercut a scarce appearance',
      'Hold inventory for the right buyer',
    ],
    timestamps: [
      { time: '0:00', label: 'Intro and target item' },
      { time: '1:20', label: 'Farm route and mobs' },
      { time: '3:30', label: 'Selling strategy' },
    ],
    mentioned: ['Goblin Power Shovel', 'Venture Co.', 'Northern Stranglethorn'],
    relatedGuideSlug: 'wow-gold-farm-goblin-power-shovel-150000',
    relatedVideos: ['600k-ghostlands-chest-farm'],
    featured: false,
  },
];
